version: '3.7'
services:
  collector-dota-nginx:
    build:
      args:
        VERSION: $NGINX_VERSION
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      target: dev
    volumes:
      - ./assets:/app/public
    depends_on:
      - collector-dota-php-fpm
    ports:
      - 8003:80

  collector-dota-php-fpm:
    build:
      args:
        VERSION: $PHP_VERSION
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
      target: dev
    volumes:
      - .:/app
    command: sh -c 'composer install --no-interaction --optimize-autoloader && php-fpm'
    depends_on:
      - collector-dota-mysql

  collector-dota-mysql:
    build:
      args:
        VERSION: $MYSQL_VERSION
      context: ./docker/mysql
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD