version: '3.7'
services:
  collector-dota-database:
    container_name: "collector-dota-database"
    image: mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vault-dota
      MYSQL_USER: vault-dota
      MYSQL_PASSWORD: vault-dota-pwd
